version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=Gestor_hoteles
      - MYSQL_USER=fp
      - MYSQL_PASSWORD=fp
    volumes:
      - ./basedatos.sql:/home/basedatos.sql